[package]
name = "pacdef"
version = "1.0.0-alpha1"
edition = "2021"

[dependencies]
alpm = "*"
anyhow = "*"
clap = "*"
path-absolutize = "*"
regex = "*"
serde_json = "*"
serde_yaml = "*"
serde_derive = "*"
serde = "*"
pacdef_macro = {path = "pacdef_macro/"}
termios = "*"

[profile.release]
lto = "off"
opt-level = "z"
strip = true

[[bin]]
name = "pacdef"
path = "src/main.rs"
