[package]
name = "pacdef"
version = "0.1.0"
edition = "2021"

[dependencies]
alpm = "*"
anyhow = "*"
# clap 4 until (at least) 4.0.32 have scrapped actual color support. we stay on 3.x until that's fixed.
clap = "3.*"
path-absolutize = "*"
regex = "*"
serde_json = "*"
pacdef_macro = {path = "pacdef_macro/"}

[profile.release]
lto = "fat"
codegen-units = 1
strip = true

[[bin]]
name = "pacdef"
path = "src/main.rs"
