[package]
name = "pacdef"
version = "1.0.0-beta3"
edition = "2021"
description = "declarative package manager for Arch Linux"
license = "GPLv3"
repository = "https://github.com/steven-omaha/pacdef"
readme = "README.md"
keywords = ["package-manager", "linux", "declarative", "cli"]
categories = ["command-line-utilities"]

[workspace]
members = ["crates/pacdef_main", "crates/pacdef_macros", "crates/pacdef_core"]

[dependencies]
alpm = "2.2"
anyhow = "1.0"
clap = "4.1"
path-absolutize = "3.0"
regex = "1.7"
termios = "0.3"

serde_json = "1.0"
serde_yaml = "0.9"
serde_derive = "1.0"
serde = "1.0"

pacdef_macros = {path = "crates/pacdef_macros", version = "0.1"}
pacdef_core = {path = "crates/pacdef_core", version = "1.0.0-beta3"}

[[bin]]
name = "pacdef"
path = "crates/pacdef_main/main.rs"

[profile.release]
lto = "off"
opt-level = "z"
strip = true
