[package]
name = "pacdef"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alpm = "*"
anyhow = "*"
clap = "*"

[profile.release]
debug = true

[dev-dependencies]
criterion = "*"

[[bench]]
harness = false
name = "bench"

