[package]
name = "pacdef"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alpm = "2.2.1"
anyhow = "1.0.66"
clap = "3.2.20"

[profile.release]
debug = true

[dev-dependencies]
criterion = "0.3.6"

[[bench]]
harness = false
name = "bench"

