[package]
name = "pacdef"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alpm = "*"
anyhow = "*"
# clap 4 until (at least) 4.0.32 have scrapped actual color support. we stay on 3.x until that's fixed.
clap = "3.*"
strum = "0.24.1"
strum_macros = "0.24.3"

[profile.release]
debug = true

[dev-dependencies]
criterion = "*"

[[bench]]
harness = false
name = "bench"

