[package]
name = "pacdef"
version = "0.1.0"
edition = "2021"

[dependencies]
alpm = "*"
anyhow = "*"
# clap 4 until (at least) 4.0.32 have scrapped actual color support. we stay on 3.x until that's fixed.
clap = "3.*"

[profile.release]
lto = "fat"
codegen-units = 1
debug = true

[dev-dependencies]
criterion = "*"

[[bench]]
harness = false
name = "bench"

