[package]
name = "pacdef"
version = "1.0.0-beta1"
edition = "2021"
description = "declarative package manager for Arch Linux"
license = "GPLv3"
repository = "https://github.com/steven-omaha/pacdef"

[dependencies]
alpm = "*"
anyhow = "*"
clap = "*"
path-absolutize = "*"
regex = "*"
serde_json = "*"
serde_yaml = "*"
serde_derive = "*"
serde = "*"
termios = "*"

pacdef_macro = {path = "pacdef_macro", version = "*"}

[profile.release]
lto = "off"
opt-level = "z"
strip = true

[[bin]]
name = "pacdef"
path = "src/main.rs"
