[package]
name = "pacdef"
version = "1.0.0-beta2"
edition = "2021"
description = "declarative package manager for Arch Linux"
license = "GPLv3"
repository = "https://github.com/steven-omaha/pacdef"

[workspace]
members = ["crates/main", "crates/macros", "crates/core"]

[dependencies]
alpm = "2.2"
anyhow = "1.0"
clap = "4.1"
path-absolutize = "3.0"
regex = "1.7"
termios = "0.3"

serde_json = "1.0"
serde_yaml = "0.9"
serde_derive = "1.0"
serde = "1.0"

macros = {path = "crates/macros", version = "0.1"}
core = {path = "crates/core", version = "1.0.0-beta2"}

[[bin]]
name = "pacdef"
path = "crates/main/main.rs"

[profile.release]
lto = "off"
opt-level = "z"
strip = true
