[package]
name = "pacdef_core"
version = "1.0.0-beta5"
edition = "2021"
description = "pacdef core library"
license = "GPLv3"
repository = "https://github.com/steven-omaha/pacdef"
readme = "README.md"
keywords = ["package-manager", "linux", "declarative", "cli"]
categories = ["command-line-utilities"]

[dependencies]
alpm = "2.2"
anyhow = {workspace = true}
clap = "4.1"
const_format = { version = "0.2", default-features = false }
path-absolutize = "3.0"
regex = "1.7"
termios = "0.3"

serde_json = "1.0"
serde_yaml = "0.9"
serde_derive = "1.0"
serde = "1.0"

pacdef_macros = {path = "../pacdef_macros", version = "0.1"}

