[package]
name = "main"
version = "1.0.0-beta2"
edition = "2021"
description = "main program for pacdef"

[[bin]]
name = "pacdef"
path = "main.rs"

[dependencies]
anyhow = "1.0"
core = { path = "../core", version = "1.0.0-beta2" }
