name: check

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'devel'
    paths:
      - 'crates/**.rs'
      - 'crates/**/Cargo.toml'
      - 'Cargo.*'
      - "clippy.toml"
  pull_request:
    branches:
      - 'main'
      - 'devel'
    paths:
      - 'crates/**.rs'
      - 'crates/**/Cargo.toml'
      - 'Cargo.*'
      - "clippy.toml"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - name: Install Packages
        run: pacman -Syu git rust clang gcc libarchive pkgconf apt --noconfirm --needed

      - name: Checkout
        uses: actions/checkout@v3

      - name: Format
        run: cargo fmt -- --check

      - name: Build
        run: cargo build --locked --features arch,debian

      - name: Clippy
        run: cargo clippy --features arch,debian -- -Dwarnings

      - name: Test
        run: cargo test --workspace --features arch,debian

