name: release

on:
  release:
    types: [created]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/archlinux/archlinux:latest
    strategy:
      matrix:
        features: [arch, debian]
    steps:
    - name: Install rust toolchain
      run: pacman -Syy --noconfirm rust
    - uses: actions/checkout@master
    - name: Build
      run: cargo build --release --features ${{ matrix.features }}
    - name: Create archive
      run: tar czf pacdef-${{ matrix.features }}.tar.gz target/release/pacdef LICENCE README.md
    - name: Upload to release
      uses: softprops/action-gh-release@v1
      with:
          files: pacdef-pacdef-${{ matrix.features }}.tar.gz
